### ISSUE TITLE
New CSR design for allowing arbitrary index base

### ISSUE THREAD

**Issue by fverdugo** [gridap/SparseMatricesCSR.jl#4]
We need (e.g., for PETSC) sparse matrices in CSR format with vectors storing values for 0-based arrays.

Implementing the CSR as a wrapper of a CSC does not work for the 0-based case (thus we need a new design).

 However, we can take advantage of the compression routines implemented for CSC, as we do now.

**Comment by fverdugo** [comment]
New type signature

```julia
# Bi is the index base (typically 0 or 1)
struct SparseMatrixCSR{Bi,Tv,Ti} <: AbstractSparseMatrix{Tv,Ti} 
  n::Int
  m::Int
  rowptr::Vector{Ti}
  colval::Vector{Ti}
  nzval::Vector{Tv}
end
```
Queries to be implemented to start with

```julia
# From abstract array interface
Base.size(a::SparseMatrixCSR)
Base.getindex(a::SparseMatrixCSR,i::Integer,j::Integer)
Base.show(io::IO, ::MIME"text/plain", S::SparseMatrixCSR)
Base.show(io::IO, S::SparseMatrixCSR)

# Sparse matrix related
SparseArrays.nnz(a::SparseMatrixCSR)
SparseArrays.nonzeros(a::SparseMatrixCSR)
SparseArrays.nzrange(a::SparseMatrixCSR, row::Integer) # output should be always in [1,n] indepentdently of Bi
SparseArrays.rowvals(a::SparseMatrixCSR) # Should return an error since it does not make sense for CSR. Use colvals instead
colvals(a::SparseMatrixCSR) # new function that replaces rowvals

# Iterative solver related
Base.*(a::SparseMatrixCSR,v::AbstractVector)
Base.mul!(y::AbstractVector,a::SparseMatrixCSR,v::AbstractVector)
```

**Comment by fverdugo** [comment]
For the symmetric case

```julia
struct SymSparseMatrixCSR{Bi,Tv,Ti} <: AbstractSparseMatrix{Tv,Ti}
  uppertrian::SparseMatrixCSR{Bi,Tv,Ti}
end
```

**Comment by fverdugo** [comment]
Creation from coo arrays

Essentially like now, using the `sparse` function and swapping i and j.

However, `colptr` and `rowval` of CSC cannot be directed assigned to `rowptr` and `colval` of CSR. We need the following transformations before
```julia
colptr[:] .-= 1-Bi
rowval[:] .-= 1-Bi 
```
 then assign
```julia
rowptr = colptr
roval = colval 
```

**Comment by victorsndvg** [comment]
We could also manage SparseMatrix conversions: 

CSC -> CSR
CSR -> CSC

**Comment by victorsndvg** [comment]
I think this is ready to merge and to release 0.4.0 in PR #3

**Comment by victorsndvg** [comment]
Comments from code review are now resolved and new release prepared.

I'm going to close this isse. Please, feel free to reopen it if needed.
